Page({
  data: {
    componentList: [
      {
        components: [
          {
            type: '布局导航',
            list: [
              {
                name: 'Container',
                nameZN: '容器',
                path: '/pages/container/index',
                tag: '新组件',
                tagType: 'danger',
              },
              {
                name: 'Title',
                nameZN: '模块标题',
                path: '/pages/title/index',
                tag: '新组件',
                tagType: 'danger',
              },
              {
                name: 'List',
                nameZN: '列表',
                path: '/pages/list/index',
              },
              {
                name: 'List-item',
                nameZN: '列表元素',
                path: '/pages/new-list/index',
                tag: '优化',
                tagType: 'success',
              },
              {
                name: 'Tabs',
                nameZN: 'Tabs',
                path: '/pages/tabs/index',
                tag: '优化',
                tagType: 'success',
              },
              {
                name: 'VTabs',
                nameZN: 'VTabs',
                path: '/pages/vtabs/index',
                tag: '优化',
                tagType: 'success',
              },
              {
                name: 'Tabs elevator',
                nameZN: 'Tabs 电梯组件',
                path: '/pages/tabs/elevator/elevator',
                tag: '优化',
                tagType: 'success',
              },
              {
                name: 'Card',
                nameZN: '卡片',
                path: '/pages/card/index',
                tag: '优化',
                tagType: 'success',
              },
              {
                name: 'Coupon',
                nameZN: '票券',
                path: '/pages/coupon/index',
                tag: '新组件',
                tagType: 'danger',
                update: true,
                updateDesc: '✍️新增票券类型',
              },
              {
                name: 'Grid',
                nameZN: '宫格',
                path: '/pages/grid/index',
                tag: '优化',
                tagType: 'success',
              },
              {
                name: 'Steps',
                nameZN: '步骤进度条',
                path: '/pages/steps/index',
                tag: '优化',
                tagType: 'success',
              },
              {
                name: 'Footer',
                nameZN: '页脚',
                path: '/pages/footer/index',
                tag: '优化',
                tagType: 'success',
                update: true,
                updateDesc: '✍️新增页脚类型',
              },
              {
                name: 'Terms',
                nameZN: '协议',
                path: '/pages/terms/index',
                tag: '新组件',
                tagType: 'danger',
              },
              {
                name: 'Flex',
                nameZN: 'Flex 布局',
                path: '/pages/flex/index',
              },
              {
                name: 'Collapse',
                nameZN: '折叠面板',
                path: '/pages/collapse/index',
                tag: '优化',
                tagType: 'success',
              },
            ],
          },
        ],
      },
      {
        components: [
          {
            type: '操作浮层',
            list: [
              {
                name: 'Popover',
                nameZN: '气泡菜单',
                path: '/pages/popover/index',
                tag: '优化',
                tagType: 'success',
              },
              {
                name: 'Filter',
                nameZN: '筛选',
                path: '/pages/filter/index',
                tag: '优化',
                tagType: 'success',
              },
              {
                name: 'Modal',
                nameZN: 'Modal',
                path: '/pages/modal/index',
                tag: '优化',
                tagType: 'success',
                update: true,
                updateDesc: '✍️小、中图的尺寸优化',
              },
              {
                name: 'PopUp',
                nameZN: '弹出菜单',
                path: '/pages/popup/index',
              },
            ],
          },
        ],
      },
      {
        components: [
          {
            type: '结果类',
            list: [
              {
                name: 'Page-result',
                nameZN: '结果页',
                path: '/pages/page-result/index',
                tag: '优化',
                tagType: 'success',
              },
              {
                name: 'Message',
                nameZN: '信息状态、操作结果',
                path: '/pages/message/index',
                tag: '优化',
                tagType: 'success',
              },
            ],
          },
        ],
      },
      {
        components: [
          {
            type: '提示引导',
            list: [
              {
                name: 'Tips',
                nameZN: '小提示、向导提示',
                path: '/pages/tips/index',
                tag: '优化',
                tagType: 'success',
              },
              {
                name: 'Notice',
                nameZN: '公告',
                path: '/pages/notice/index',
                tag: '优化',
                tagType: 'success',
                update: true,
                updateDesc: '✍️调整通告栏类型及表现方式',
              },
              {
                name: 'Badge',
                nameZN: '红点，徽标',
                path: '/pages/badge/index',
                tag: '优化',
                tagType: 'success',
              },
              {
                name: 'Tag',
                nameZN: ' 标签',
                path: '/pages/tag/index',
                tag: '新组件',
                tagType: 'danger',
              },
              {
                name: 'Mask',
                nameZN: '背景蒙层',
                path: '/pages/mask/mask',
                tag: '新组件',
                tagType: 'danger',
              },
              {
                name: 'Guide',
                nameZN: '遮罩引导',
                path: '/pages/guide/guide',
                tag: '新组件',
                tagType: 'danger',
              },
              {
                name: 'Avatar',
                nameZN: '头像',
                path: '/pages/avatar/index',
                tag: '新组件',
                tagType: 'danger',
                update: true,
                updateDesc: '✍️调整头像尺寸及文字大小',
              },
            ],
          },
        ],
      },
      {
        components: [
          {
            type: '表单类',
            list: [
              {
                name: 'Form',
                nameZN: '表单',
                path: '/pages/form/index',
                tag: '优化',
                tagType: 'success',
              },
              {
                name: 'Input-item',
                nameZN: '输入框',
                path: '/pages/input-item/index',
                tag: '优化',
                tagType: 'success',
                update: true,
                updateDesc: '✍️新增垂直输入框',
              },
              {
                name: 'Picker-item',
                nameZN: '选择框',
                path: '/pages/picker-item/index',
                tag: '优化',
                tagType: 'success',
                update: true,
                updateDesc: '✍️新增垂直选择框',
              },
              {
                name: 'Verify-code',
                nameZN: '验证码框',
                path: '/pages/verify-code/index',
                tag: '新组件',
                tagType: 'danger',
              },
              {
                name: 'Long-password',
                nameZN: '长密码框',
                path: '/pages/long-password/index',
                tag: '新组件',
                tagType: 'danger',
              },
              {
                name: 'Multi-liner',
                nameZN: '多行输入',
                path: '/pages/multi-liner/index',
                tag: '新组件',
                tagType: 'danger',
              },
              {
                name: 'Amount-input',
                nameZN: '金额输入',
                path: '/pages/amount-input/index',
                tag: '优化',
                tagType: 'success',
              },
              {
                name: 'Button',
                nameZN: '按钮',
                path: '/pages/button/index',
                tag: '新组件',
                tagType: 'danger',
              },
              {
                name: 'Am-switch',
                nameZN: '开关',
                path: '/pages/am-switch/index',
                tag: '新组件',
                tagType: 'danger',
              },
              {
                name: 'Am-checkbox',
                nameZN: '复选框',
                path: '/pages/am-checkbox/index',
                tag: '新组件',
                tagType: 'danger',
              },
              {
                name: 'Am-radio',
                nameZN: '单选框',
                path: '/pages/am-radio/index',
                tag: '新组件',
                tagType: 'danger',
              },
              {
                name: 'Search-bar',
                nameZN: '搜索框',
                path: '/pages/search-bar/index',
                tag: '优化',
                tagType: 'success',
              },
            ],
          },
        ],
      },
      {
        components: [
          {
            type: '手势类',
            list: [
              {
                name: 'Swipe-action',
                nameZN: '滑动删除',
                path: '/pages/swipe-action/index',
                tag: '优化',
                tagType: 'success',
              },
            ],
          },
        ],
      },
      {
        components: [
          {
            type: '其他',
            list: [
              {
                name: 'Pagination',
                nameZN: '分页',
                path: '/pages/pagination/index',
                tag: '优化',
                tagType: 'success',
              },
              {
                name: 'Alphabet',
                nameZN: '字母检索表',
                path: '/pages/alphabet/index',
                tag: '新组件',
                tagType: 'danger',
              },
              {
                name: 'Stepper',
                nameZN: 'Stepper',
                path: '/pages/stepper/index',
                tag: '优化',
                tagType: 'success',
              },
              {
                name: 'Calendar',
                nameZN: '日历',
                path: '/pages/calendar/index',
                tag: '优化',
                tagType: 'success',
              },
              {
                name: 'Am-icon',
                nameZN: '图标',
                path: '/pages/am-icon/index',
                tag: '优化',
                tagType: 'success',
              },
              {
                name: 'Loading',
                nameZN: 'loading 加载',
                path: '/pages/loading/loading',
                tag: '新组件',
                tagType: 'danger',
              },
            ],
          },
        ],
      },
    ],
    // components: [
    //   // {
    //   //   name: 'InputItem',
    //   //   nameZN: '（旧组件）列表输入项',
    //   //   path: '/pages/input-item/index',
    //   // },
    //   // {
    //   //   name: 'PickerItem',
    //   //   nameZN: '（旧组件）选择输入项',
    //   //   path: '/pages/picker-item/index',
    //   // },
    // ],
  },
});
